### ISSUE TITLE
Erro no codigo

### ISSUE THREAD

**Issue by Mikaa69** [Wendelzin10/projetinho_de_loteria_simulador#2]
O erro está relacionado a entrada de dados sem digitar nenhum numero consigo fazer o sorteio. @Wendelzin10 burro corrija isso

**Comment by Mikaa69** [comment]
TU É TAO PRETO QUE NO ESCONDE ESCONDE TA DE HACKER

**Comment by Mikaa69** [comment]
não é um erro mas a linha lá esta limpando a variável para novo sorteio

**Comment by Mikaa69** [comment]
P
R
E
T
O

**Comment by Wendelzin10** [comment]
Cala boca vagabunda
